#! /bin/bash

home_dir=~
cd `dirname $0`
dotfiles_dir=`pwd -P`

for f in ackrc gitconfig gitignore_global inputrc shell_aliases shell_functions shell_servers vim bash xmodmap zsh; do
    if [ -L $home_dir/.$f ]; then
        rm $home_dir/.$f
    fi
    if [ -e $home_dir/.$f ]; then
	echo $home_dir/.$f exists
    fi
    if [ ! -e $dotfiles_dir/$f ]; then
	echo $dotfiles_dir/$f doesnt exist
    fi
    if [ ! -e $home_dir/.$f -a -e $dotfiles_dir/$f ]; then
        ln -s $dotfiles_dir/$f $home_dir/.$f
    fi
done

# .vim/*
if [ -L $home_dir/.vimrc ]; then rm $home_dir/.vimrc; fi
if [ -e $home_dir/.vim ]; then
    if [ ! -e $home_dir/.vimrc ]; then ln -s $home_dir/.vim/vimrc $home_dir/.vimrc; fi
    if [ ! -d $home_dir/.vim/plugin ]; then mkdir $home_dir/.vim/plugin; fi
    if [ -f $home_dir/.vim/bundle/dbgpclient/plugin/debugger.py ]; then
        if [ -L $home_dir/.vim/plugin/debugger.py ]; then rm $home_dir/.vim/plugin/debugger.py; fi
        ln -s ../bundle/dbgpclient/plugin/debugger.py $home_dir/.vim/plugin/debugger.py
    fi
    if [ -d $home_dir/.vim/bundle/commandt ]; then
        # requires ruby, ruby1.8-dev
        cd $home_dir/.vim/bundle/commandt/ruby/command-t
        ruby extconf.rb
        make
    fi
    cd ~
fi

# .bash/*
for f in _profile rc; do
    if [ -L $home_dir/.bash$f ]; then
        rm $home_dir/.bash$f
    fi
    if [ ! -e $home_dir/.bash$f -a -e $home_dir/.bash/bash$f ]; then
        ln -s $home_dir/.bash/bash$f $home_dir/.bash$f
    fi
done
# .zsh/*
for f in login profile shenv shrc; do
    if [ -L $home_dir/.z$f ]; then
        rm $home_dir/.z$f
    fi
    if [ ! -e $home_dir/.z$f -a -e $home_dir/.zsh/z$f ]; then
        ln -s $home_dir/.zsh/z$f .z$f
    fi
done
